---
dist: xenial
install:
  - "pip install discord.py pytest pydocstyle"
language: python
python:
  - "3.7"
script:
  - pytest test_Goku.py
  - pydocstyle Goku.py
notifications:
  email:
    recipients:
      - user@example.com
    on_success: always
    on_failure: always
