---
dist: xenial
install:
  - "pip install discord.py pytest pylint pycodestyle pydocstyle"
language: python
python:
  - "3.7"
script:
  - pytest
  - pydocstyle Goku.py
notifications:
  email:
    recipients:
      - user@example.com
    on_success: always
    on_failure: always
